-- Table: location
-- Stores location codes and their corresponding hints
CREATE TABLE location (
    location_code TEXT PRIMARY KEY,
    location_hint TEXT NOT NULL
);

-- Table: team_no
-- Stores team information and members
CREATE TABLE team_no (
    team TEXT PRIMARY KEY,
    member1 TEXT,
    member2 TEXT,
    member3 TEXT,
    member4 TEXT
);

-- Table: setlocation
-- Stores the assigned path/route for each team
CREATE TABLE setlocation (
    team TEXT PRIMARY KEY REFERENCES team_no(team),
    start TEXT DEFAULT 'CLG',
    location1 TEXT REFERENCES location(location_code),
    location2 TEXT REFERENCES location(location_code),
    location3 TEXT REFERENCES location(location_code),
    location4 TEXT REFERENCES location(location_code),
    location5 TEXT REFERENCES location(location_code),
    "end" TEXT DEFAULT 'CLG'
);

-- Table: verifylocation
-- Tracks the progress of each team through their assigned locations
CREATE TABLE verifylocation (
    team TEXT PRIMARY KEY REFERENCES team_no(team),
    start TEXT,
    start_time TIMESTAMP WITH TIME ZONE,
    location1 TEXT,
    location1_time TIMESTAMP WITH TIME ZONE,
    location2 TEXT,
    location2_time TIMESTAMP WITH TIME ZONE,
    location3 TEXT,
    location3_time TIMESTAMP WITH TIME ZONE,
    location4 TEXT,
    location4_time TIMESTAMP WITH TIME ZONE,
    location5 TEXT,
    location5_time TIMESTAMP WITH TIME ZONE,
    "end" TEXT
);

-- Table: register
-- Logs successful location checks/verifications
CREATE TABLE register (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    team_name TEXT REFERENCES team_no(team),
    time TIME, -- Storing only time as per server.js logic
    location TEXT
);
